// mocks/notes_writer.go
package mocks

import (
	"github.com/GuilhermeFujita/nlw_notes_api/database/model"
	"github.com/GuilhermeFujita/nlw_notes_api/dto"
	"github.com/stretchr/testify/mock"
)

// NotesWriter is an autogenerated mock type for the NotesWriter interface
type NotesWriter struct {
	mock.Mock
}

// SaveNote provides a mock function with given fields: note
func (_m *NotesWriter) SaveNote(note dto.NoteRequestDTO) (model.Note, error) {
	ret := _m.Called(note)

	var r0 model.Note
	if rf, ok := ret.Get(0).(func(dto.NoteRequestDTO) model.Note); ok {
		r0 = rf(note)
	} else {
		r0 = ret.Get(0).(model.Note)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.NoteRequestDTO) error); ok {
		r1 = rf(note)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNote provides a mock function with given fields: note
func (_m *NotesWriter) DeleteNote(note model.Note) error {
	ret := _m.Called(note)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Note) error); ok {
		r0 = rf(note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
