// mocks/notes_finder.go
package mocks

import (
	"github.com/GuilhermeFujita/nlw_notes_api/database/model"
	"github.com/stretchr/testify/mock"
)

// NotesFinder is an autogenerated mock type for the NotesFinder interface
type NotesFinder struct {
	mock.Mock
}

// GetNotes provides a mock function with given fields: searchedNote
func (_m *NotesFinder) GetNotes(searchedNote string) ([]model.Note, error) {
	ret := _m.Called(searchedNote)

	var r0 []model.Note
	if rf, ok := ret.Get(0).(func(string) []model.Note); ok {
		r0 = rf(searchedNote)
	} else {
		r0 = ret.Get(0).([]model.Note)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(searchedNote)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNote provides a mock function with given fields: id
func (_m *NotesFinder) GetNote(id int) (model.Note, error) {
	ret := _m.Called(id)

	var r0 model.Note
	if rf, ok := ret.Get(0).(func(int) model.Note); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Note)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
